task: detection

num_classes: 80
remap_mscoco_category: True

train_dataloader:
  type: DataLoader
  dataset:
    type: StaigeDataset
    annotations_file: ./dataset/train.csv
    img_dir: ./dataset
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 1
  num_workers: 4
  drop_last: True


val_dataloader:
  type: DataLoader
  dataset:
    type: StaigeDataset
    annotations_file: ./dataset/eval.csv
    img_dir: ./dataset
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  batch_size: 1
  num_workers: 4
  drop_last: False
